#include "TrainingPreset.h"
#include <algorithm>
#include <fstream>
namespace{
std::string Escape(const std::string&s){std::string r;for(char c:s){if(c=='\\')r+="\\\\";else if(c=='\"')r+="\\\"";else r+=c;}return r;}
bool Read(const std::filesystem::path&p,std::string&t){std::ifstream s(p,std::ios::binary);if(!s)return false;t.assign(std::istreambuf_iterator<char>(s),{});return true;}
bool S(const std::string&j,const char*k,std::string&v){auto p=j.find(std::string("\"")+k+"\"");if(p==std::string::npos)return false;p=j.find('"',j.find(':',p));if(p==std::string::npos)return false;auto e=j.find('"',p+1);if(e==std::string::npos)return false;v=j.substr(p+1,e-p-1);return true;}
bool N(const std::string&j,const char*k,double&v){auto p=j.find(std::string("\"")+k+"\"");if(p==std::string::npos)return false;p=j.find(':',p);try{v=std::stod(j.substr(p+1));return true;}catch(...){return false;}}
bool B(const std::string&j,const char*k,bool&v){auto p=j.find(std::string("\"")+k+"\"");if(p==std::string::npos)return false;p=j.find(':',p);auto a=j.find_first_not_of(" \t\r\n",p+1);v=j.compare(a,4,"true")==0;return true;}
}
bool TrainingPreset::Save(const std::filesystem::path&root,std::string&error)const{std::error_code ec;std::filesystem::create_directories(root,ec);if(ec){error=ec.message();return false;}std::ofstream s(root/(name+".json"),std::ios::binary|std::ios::trunc);if(!s){error="Could not write training preset.";return false;}s<<"{\n  \"version\": 1,\n  \"name\": \""<<Escape(name)<<"\",\n  \"resolution\": "<<resolution<<",\n  \"epochs\": "<<epochs<<",\n  \"batch_size\": "<<batchSize<<",\n  \"gradient_accumulation\": "<<gradientAccumulation<<",\n  \"learning_rate\": "<<learningRate<<",\n  \"rank\": "<<rank<<",\n  \"mixed_precision\": \""<<Escape(mixedPrecision)<<"\",\n  \"gradient_checkpointing\": "<<(gradientCheckpointing?"true":"false")<<",\n  \"seed\": "<<seed<<"\n}\n";return !!s;}
bool TrainingPreset::Load(const std::filesystem::path&p,TrainingPreset&x,std::string&error){std::string j;if(!Read(p,j)){error="Could not read training preset.";return false;}double n;if(!S(j,"name",x.name)){error="Invalid training preset.";return false;}if(N(j,"resolution",n))x.resolution=(int)n;if(N(j,"epochs",n))x.epochs=(int)n;if(N(j,"batch_size",n))x.batchSize=(int)n;if(N(j,"gradient_accumulation",n))x.gradientAccumulation=(int)n;if(N(j,"learning_rate",n))x.learningRate=(float)n;if(N(j,"rank",n))x.rank=(int)n;S(j,"mixed_precision",x.mixedPrecision);B(j,"gradient_checkpointing",x.gradientCheckpointing);if(N(j,"seed",n))x.seed=(int)n;return true;}
std::vector<TrainingPreset> ScanTrainingPresets(const std::filesystem::path&r,std::string&w){w.clear();std::vector<TrainingPreset>v;std::error_code ec;if(!std::filesystem::exists(r,ec))return v;for(auto&e:std::filesystem::directory_iterator(r))if(e.path().extension()==".json"){TrainingPreset p;std::string x;if(TrainingPreset::Load(e.path(),p,x))v.push_back(p);else if(w.empty())w=x;}std::ranges::sort(v,{},&TrainingPreset::name);return v;}
bool EnsureDefaultTrainingPresets(const std::filesystem::path&r,std::string&e){std::error_code ec;if(!std::filesystem::exists(r/"Quick Test.json")){TrainingPreset p;p.name="Quick Test";p.epochs=3;p.rank=8;if(!p.Save(r,e))return false;}if(!std::filesystem::exists(r/"Style Quality.json")){TrainingPreset p;p.name="Style Quality";p.epochs=8;p.rank=16;if(!p.Save(r,e))return false;}return true;}
